# Generated by Django 5.2.5 on 2025-08-22 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsianRangeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('high', models.DecimalField(decimal_places=5, max_digits=10)),
                ('low', models.DecimalField(decimal_places=5, max_digits=10)),
                ('midpoint', models.DecimalField(decimal_places=5, max_digits=10)),
                ('range_pips', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grade', models.CharField(max_length=20)),
                ('risk_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'asian_range_data',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MT5Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField()),
                ('server', models.CharField(default='MetaQuotes-Demo', max_length=100)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='connected', max_length=20)),
            ],
            options={
                'db_table': 'mt5_connection',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'trade_signal',
                'ordering': ['-created_at'],
            },
        ),
    ]
