# Generated by Django 5.2.5 on 2025-08-22 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('release_time', models.DateTimeField()),
                ('severity', models.CharField(choices=[('LOW', 'Low Impact'), ('MEDIUM', 'Medium Impact'), ('HIGH', 'High Impact'), ('CRITICAL', 'Critical Impact')], max_length=20)),
                ('buffer_minutes', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'economic_news',
                'ordering': ['-release_time'],
            },
        ),
        migrations.CreateModel(
            name='LiquiditySweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='XAUUSD', max_length=20)),
                ('sweep_direction', models.CharField(max_length=10)),
                ('sweep_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sweep_threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sweep_time', models.DateTimeField()),
                ('confirmation_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('confirmation_time', models.DateTimeField(blank=True, null=True)),
                ('displacement_atr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('displacement_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(default='DETECTED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'liquidity_sweep',
                'ordering': ['-sweep_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('component', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('ASIAN', 'Asian Session'), ('LONDON', 'London Session'), ('NEW_YORK', 'New York Session')], max_length=20)),
                ('current_state', models.CharField(choices=[('IDLE', 'Idle'), ('SWEPT', 'Sweep Detected'), ('CONFIRMED', 'Reversal Confirmed'), ('ARMED', 'Armed for Entry'), ('IN_TRADE', 'In Trade'), ('COOLDOWN', 'Cooldown')], default='IDLE', max_length=20)),
                ('asian_range_high', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('asian_range_low', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('asian_range_midpoint', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('asian_range_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('asian_range_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('sweep_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sweep_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('sweep_time', models.DateTimeField(blank=True, null=True)),
                ('confirmation_time', models.DateTimeField(blank=True, null=True)),
                ('armed_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trading_session',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tradesignal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tradesignal',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='gpt_opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='gpt_tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='risk_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='risk_reward_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('SWEPT', 'Sweep Detected'), ('CONFIRMED', 'Reversal Confirmed'), ('ARMED', 'Armed for Entry'), ('IN_TRADE', 'In Trade'), ('COOLDOWN', 'Cooldown')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='take_profit_1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='take_profit_2',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='stop_loss',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='symbol',
            field=models.CharField(default='XAUUSD', max_length=20),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='sweep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.liquiditysweep'),
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('atr_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adx_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_data_symbol_2d3fa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('execution_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('execution_time', models.DateTimeField()),
                ('status', models.CharField(default='EXECUTED', max_length=20)),
                ('stop_loss_hit', models.BooleanField(default=False)),
                ('take_profit_1_hit', models.BooleanField(default=False)),
                ('take_profit_2_hit', models.BooleanField(default=False)),
                ('breakeven_moved', models.BooleanField(default=False)),
                ('trailing_stop_active', models.BooleanField(default=False)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradesignal')),
            ],
            options={
                'db_table': 'trade_execution',
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='TradeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('action_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradeexecution')),
            ],
            options={
                'db_table': 'trade_management',
                'ordering': ['-action_time'],
            },
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradingsession'),
        ),
        migrations.CreateModel(
            name='GPTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=20)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField()),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('decision', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradesignal')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradingsession')),
            ],
            options={
                'db_table': 'gpt_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfluenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('bias', models.CharField(max_length=20)),
                ('trend_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('atr_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adx_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocity_spike', models.BooleanField(default=False)),
                ('news_risk', models.BooleanField(default=False)),
                ('news_buffer_minutes', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradingsession')),
            ],
            options={
                'db_table': 'confluence_check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mt5_integration.tradingsession'),
        ),
    ]
