# Generated by Django 5.2.5 on 2025-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0002_economicnews_liquiditysweep_systemlog_tradingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='atr_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='bos_choch_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='cooldown_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='current_daily_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='current_daily_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='daily_bias',
            field=models.CharField(blank=True, choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='daily_loss_limit',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='daily_trade_count_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='displacement_atr_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='h4_bias',
            field=models.CharField(blank=True, choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='spread_pips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='sweep_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
