# Generated by Django 5.2.5 on 2025-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0005_delete_economicnews_remove_tradeexecution_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='symbol',
            field=models.CharField(default='XAUUSD', max_length=16),
        ),
    ]
