# Generated by Django 5.2.5 on 2025-09-03 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5_integration', '0006_tradingsession_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low Impact'), ('MEDIUM', 'Medium Impact'), ('HIGH', 'High Impact'), ('CRITICAL', 'Critical Impact')], max_length=10)),
                ('tier', models.CharField(blank=True, choices=[('TIER1', 'Tier 1 (FOMC, CPI, NFP)'), ('OTHER', 'Other High Impact')], max_length=10, null=True)),
                ('release_time', models.DateTimeField()),
                ('actual_value', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_value', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_value', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'economic_news',
                'ordering': ['-release_time'],
            },
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='adx_timeframe',
            field=models.CharField(default='15m', max_length=10),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='auction_blackout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='failure_reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='h1_band_walk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='london_traversed_asia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='news_tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='ny_requires_fresh_sweep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='participation_filter_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='spread_threshold',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='trend_day_high_adx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencecheck',
            name='velocity_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='acceptance_outside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='atr_h1_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='both_sides_swept_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='chosen_threshold_component',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='confirm_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='threshold_from_atr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='threshold_from_floor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='liquiditysweep',
            name='threshold_from_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='breakeven_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='calculated_r',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='entry_method',
            field=models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('CONFIRM_ON_TRIGGER', 'Confirm on Trigger')], default='LIMIT', max_length=20),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='entry_zone_reference',
            field=models.CharField(choices=[('CONFIRM_BODY', 'Confirmation Candle Body'), ('OB_FVG', 'Order Block / Fair Value Gap'), ('ASIAN_MIDPOINT', 'Asian Midpoint')], default='CONFIRM_BODY', max_length=20),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='micro_trigger_satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='retest_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='sl_pips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='tp1_pips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='tp2_pips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='trailing_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='confluencecheck',
            index=models.Index(fields=['session', 'passed'], name='confluence__session_03d948_idx'),
        ),
        migrations.AddIndex(
            model_name='confluencecheck',
            index=models.Index(fields=['created_at', 'timeframe'], name='confluence__created_9ce736_idx'),
        ),
        migrations.AddIndex(
            model_name='liquiditysweep',
            index=models.Index(fields=['session', 'sweep_direction'], name='liquidity_s_session_540d47_idx'),
        ),
        migrations.AddIndex(
            model_name='liquiditysweep',
            index=models.Index(fields=['sweep_time', 'status'], name='liquidity_s_sweep_t_5768e6_idx'),
        ),
        migrations.AddIndex(
            model_name='liquiditysweep',
            index=models.Index(fields=['symbol', 'created_at'], name='liquidity_s_symbol_f68ede_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['session', 'state'], name='trade_signa_session_5ae577_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['symbol', 'created_at'], name='trade_signa_symbol_ba9cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['state', 'retest_expiry_time'], name='trade_signa_state_26cec2_idx'),
        ),
        migrations.AddIndex(
            model_name='economicnews',
            index=models.Index(fields=['release_time', 'severity'], name='economic_ne_release_175388_idx'),
        ),
        migrations.AddIndex(
            model_name='economicnews',
            index=models.Index(fields=['currency', 'tier'], name='economic_ne_currenc_edf4bd_idx'),
        ),
    ]
